# Generated by Django 5.1.6 on 2025-02-28 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicrecs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='recommendation',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
