# Generated by Django 5.1.6 on 2025-05-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicrecs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'managed': True},
        ),
    ]
