# Generated by Django 5.1.6 on 2025-05-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicrecs', '0002_alter_track_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
