# Generated by Django 5.1.6 on 2025-05-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicrecs', '0003_alter_track_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='mp3_file',
            field=models.FileField(blank=True, null=True, upload_to='tracks_mp3/'),
        ),
    ]
