# Generated by Django 5.1.6 on 2025-05-27 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicrecs', '0004_track_mp3_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='mp3_file',
        ),
    ]
